import { GameConfig, GameId } from "@/types/game";
import { Suit, Rank } from "@/types/mission";

export const starbreakerConfig: GameConfig = {
  id: GameId.STARBREAKER,
  name: "Starbreaker",
  logo: "/Starbreaker_Logo.png",
  logoAlt: "Starbreaker",
  tagline: "Generate adventures using the card-based system",
  copyright: "Starbreaker is ©2025 Star Anvil Studios",
  studioLogo: "/Star Anvil Logo NB.png",
  studioUrl: "https://staranvilstudios.com/",
  primaryColor: "#1a4d7a", // Deep space blue
  accentColor: "#00d9ff", // Cyan tech accent
  missionData: {
    // STEP 1: ANTAGONIST FACTION (SAINT)
    locations: {
      [Rank.TWO]: "Belters Union",
      [Rank.THREE]: "Blood Coin",
      [Rank.FOUR]: "Bratva",
      [Rank.FIVE]: "Cartel",
      [Rank.SIX]: "Jarisk'Krim",
      [Rank.SEVEN]: "Mafia",
      [Rank.EIGHT]: "Monarchs",
      [Rank.NINE]: "Splicers",
      [Rank.TEN]: "Sydok",
      [Rank.JACK]: "Triad",
      [Rank.QUEEN]: "Void",
      [Rank.KING]: "Yakuza",
      [Rank.ACE]: "Other faction",
    },
    locationSuitModifiers: {
      [Suit.CLUBS]: "SAINT Antagonist Faction",
      [Suit.DIAMONDS]: "SAINT Antagonist Faction",
      [Suit.HEARTS]: "SAINT Antagonist Faction",
      [Suit.SPADES]: "SAINT Antagonist Faction",
    },

    // STEP 2: CAST OF CHARACTERS - Face Cards
    goals: {
      [Rank.TWO]: "Draw from Number Deck",
      [Rank.THREE]: "Draw from Number Deck",
      [Rank.FOUR]: "Draw from Number Deck",
      [Rank.FIVE]: "Draw from Number Deck",
      [Rank.SIX]: "Draw from Number Deck",
      [Rank.SEVEN]: "Draw from Number Deck",
      [Rank.EIGHT]: "Draw from Number Deck",
      [Rank.NINE]: "Draw from Number Deck",
      [Rank.TEN]: "Draw from Number Deck",
      [Rank.JACK]: "Specialist: Bounty hunter, assassin, scientist, engineer, or lawyer",
      [Rank.QUEEN]: "Fatale: Manipulates through blackmail, bribery, or seduction",
      [Rank.KING]: "Consigliere: Mini-boss administrator, strategist, or field commander",
      [Rank.ACE]: "Mastermind: Brilliant enemy leader who confounds heroes",
    },
    goalSuitModifiers: {
      [Suit.CLUBS]: "Obstacle: Don't need to fight them, just get around them",
      [Suit.DIAMONDS]: "Treasure: Keys to or targets of the mission",
      [Suit.HEARTS]: "Fellow Traveler: Family, friends, lovers with ties to the Syndicate",
      [Suit.SPADES]: "Enemy: True believers who must be met with force",
    },

    // STEP 3: MISSION PROFILE - Suit determines type, crew type affects details
    objects: {
      [Suit.CLUBS]: {
        [Rank.TWO]: "Acquire - Object",
        [Rank.THREE]: "Broker - Business",
        [Rank.FOUR]: "Coerce - Business",
        [Rank.FIVE]: "Disrupt - Operation",
        [Rank.SIX]: "Disrupt - Operation",
        [Rank.SEVEN]: "Eliminate - Location",
        [Rank.EIGHT]: "Investigate - Internal Affairs",
        [Rank.NINE]: "Protect - Complication",
        [Rank.TEN]: "Transport - Complication",
        [Rank.JACK]: "Fellow Traveler - Friend",
        [Rank.QUEEN]: "Obstacle - Admirer",
        [Rank.KING]: "Obstacle - Authority",
        [Rank.ACE]: "Obstacle - The Law",
      },
      [Suit.DIAMONDS]: {
        [Rank.TWO]: "Acquire - Valuables",
        [Rank.THREE]: "Broker - Information",
        [Rank.FOUR]: "Coerce - Information",
        [Rank.FIVE]: "Disrupt - Interception",
        [Rank.SIX]: "Disrupt - Interception",
        [Rank.SEVEN]: "Eliminate - Secret",
        [Rank.EIGHT]: "Investigate - Snitch",
        [Rank.NINE]: "Protect - Knowledge",
        [Rank.TEN]: "Transport - Knowledge",
        [Rank.JACK]: "Treasure - Expert",
        [Rank.QUEEN]: "Treasure - Associate",
        [Rank.KING]: "Treasure - Backer",
        [Rank.ACE]: "Treasure - Boss",
      },
      [Suit.HEARTS]: {
        [Rank.TWO]: "Acquire - Person",
        [Rank.THREE]: "Broker - Services",
        [Rank.FOUR]: "Coerce - Services",
        [Rank.FIVE]: "Disrupt - Relationship",
        [Rank.SIX]: "Disrupt - Relationship",
        [Rank.SEVEN]: "Eliminate - Person",
        [Rank.EIGHT]: "Investigate - Murder",
        [Rank.NINE]: "Protect - Person",
        [Rank.TEN]: "Transport - Person",
        [Rank.JACK]: "Fellow Traveler - Friend",
        [Rank.QUEEN]: "Fellow Traveler - Lover",
        [Rank.KING]: "Fellow Traveler - Mentor",
        [Rank.ACE]: "Fellow Traveler - Family Member",
      },
      [Suit.SPADES]: {
        [Rank.TWO]: "Acquire - Valuables",
        [Rank.THREE]: "Broker - Goods",
        [Rank.FOUR]: "Coerce - Goods",
        [Rank.FIVE]: "Disrupt - Production",
        [Rank.SIX]: "Disrupt - Production",
        [Rank.SEVEN]: "Eliminate - Thing",
        [Rank.EIGHT]: "Investigate - Theft",
        [Rank.NINE]: "Protect - Thing",
        [Rank.TEN]: "Transport - Object",
        [Rank.JACK]: "Enemy - Specialist",
        [Rank.QUEEN]: "Enemy - Fatale",
        [Rank.KING]: "Enemy - Consigliere",
        [Rank.ACE]: "Enemy - Mastermind",
      },
    },
    objectSuitLabels: {
      [Suit.CLUBS]: "Complication",
      [Suit.DIAMONDS]: "Knowledge/Treasure",
      [Suit.HEARTS]: "Person/Relationship",
      [Suit.SPADES]: "Thing/Enemy",
    },

    // ANTAGONIST FACTION (SYNDICATE) - for obstacle
    obstacles: {
      [Rank.TWO]: "Assassins Guild",
      [Rank.THREE]: "Bounty Hunters League",
      [Rank.FOUR]: "Outlaw Gravcycle Club",
      [Rank.FIVE]: "Pirates of the Oridium Nebula",
      [Rank.SIX]: "Atlantica Ship Works",
      [Rank.SEVEN]: "Gorsht Manufacturing",
      [Rank.EIGHT]: "Praxor & Gimble Pharmaceuticals",
      [Rank.NINE]: "Remis Engineering",
      [Rank.TEN]: "Vizon Corp",
      [Rank.JACK]: "Arusan Trade Conglomerate",
      [Rank.QUEEN]: "Vulkolasi Union",
      [Rank.KING]: "Star Systems Alliance",
      [Rank.ACE]: "Other government",
    },
    obstacleSuitModifiers: {
      [Suit.CLUBS]: "Syndicate Antagonist Faction",
      [Suit.DIAMONDS]: "Syndicate Antagonist Faction",
      [Suit.HEARTS]: "Syndicate Antagonist Faction",
      [Suit.SPADES]: "Syndicate Antagonist Faction",
    },

    // TWIST - Additional context or complications
    twists: {
      [Rank.TWO]: "Heist Team specialty",
      [Rank.THREE]: "Infiltrators or Troubleshooters specialty",
      [Rank.FOUR]: "Multiple crew types",
      [Rank.FIVE]: "Strike Unit or Enforcers specialty",
      [Rank.SIX]: "Multiple crew types",
      [Rank.SEVEN]: "Mixed specialty mission",
      [Rank.EIGHT]: "Investigation-focused mission",
      [Rank.NINE]: "Protection-focused mission",
      [Rank.TEN]: "Transport mission for all crews",
      [Rank.JACK]: "Draw additional Mission Profile card",
      [Rank.QUEEN]: "Draw additional Mission Profile card",
      [Rank.KING]: "Draw additional Mission Profile card",
      [Rank.ACE]: "Special: Choose from alternatives or roll",
    },
    twistSuitModifiers: {
      [Suit.CLUBS]: "Complication: Something weird or hard to manage",
      [Suit.DIAMONDS]: "Knowledge or Intelligence: Data must be protected or acquired",
      [Suit.HEARTS]: "Relationship: Personal connections complicate the mission",
      [Suit.SPADES]: "Combat: Violence is likely or necessary",
    },
  },
};
